### ISSUE TITLE
Can't run for desktop window

### ISSUE THREAD

**Issue by akunzz** [abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard#13]
Can't run for desktop window

**Comment by arunkpatra** [comment]
@akunzz Can you please provide details around errors you are getting and provide any stack traces etc. Also please specify steps to reproduce your errors.

You can easily help the community to help you better by providing relevant details in your issue.

**Comment by akunzz** [comment]
![screenshot_1623392456](https://user-images.githubusercontent.com/22209164/121640284-ed0fe580-cab7-11eb-8dd5-ab701ffcd684.png)
Here is error

**Comment by arunkpatra** [comment]
Oh ok. This project currently does not support the Windows platform.

**Comment by ajumalp** [comment]
Expand this folder into your project folder, it's working fine for me. 

[windows.zip](https://github.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard/files/6644447/windows.zip)

**Comment by akunzz** [comment]
> Expand this folder into your project folder, it's working fine for me.
> 
> [windows.zip](https://github.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard/files/6644447/windows.zip)

thanks so much! It working for me!

**Comment by Gizmo1337** [comment]
> Expand this folder into your project folder, it's working fine for me.
> 
> [windows.zip](https://github.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard/files/6644447/windows.zip)

should be a pull request

**Comment by ajumalp** [comment]
> > Expand this folder into your project folder, it's working fine for me.
> > [windows.zip](https://github.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard/files/6644447/windows.zip)
> 
> should be a pull request

Added 👍🏻

**Comment by abuanwar072** [comment]
Fixed, check the latest update.
