### ISSUE TITLE
Error on iPhone 5/SE - Bottom Overflowed By 11 Px

### ISSUE THREAD

**Issue by syedadeel2** [abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard#15]
![image](https://user-images.githubusercontent.com/2682457/122660093-b164d200-d1c1-11eb-9ac2-6b0cf37993d1.png)

**Comment by Gizmo1337** [comment]
In file lib/screens/dashboard/components/my_fields.dart line 43, change chialdAspectRatio teranary true value from 1.3 to 1.
![image](https://user-images.githubusercontent.com/25569867/122666719-c0df1d80-d1b7-11eb-8939-7c0c05ed6e21.png)

**Comment by akcauser** [comment]
fixed in this pr. 

https://github.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard/pull/24
