### ISSUE TITLE
How drawer click works?

### ISSUE THREAD

**Issue by zanpen2000** [abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard#36]
Hi!, I'm newer of flutter, I clone the whole project and can not find the code of drawer item click. 

I want some working code to learn how drawer item click, can any body help me ? 

that would be very help for me!  THANKS!!!

**Comment by hardiklakhalani** [comment]
From `main_screen.dart` Follow this `SideMenu()` widget (by Ctrl+Click on it) and you will reach...
![image](https://user-images.githubusercontent.com/82162165/144751614-766ca19d-b55f-4902-811d-2589fc623337.png)

Right here--> there is a "press" parameter assigned to the underlying ListTile's onTap property.
![image](https://user-images.githubusercontent.com/82162165/144751637-83a7b9df-62f7-477b-b69c-a20a388a5e95.png)

**Comment by hustler-manishdayma** [comment]
If You want to open Drawer programmatically then just write this code in inkwell or any tap method to run this.

`Scaffold.of(context).openDrawer();`

**Comment by zanpen2000** [comment]
@hustler-manishdayma 

Thanks for your answers.

Maybe I didn’t make it clear, what I mean is, how to respond to the click event of the menu item can realize the "partial refresh" of the page on the right, because I designed the display page on the right into two parts, the upper part is the public part, click The menu item is not refreshed (such as the login user name), and the following part uses the datatable2 component to refresh.

Currently, I use the IndexStacked component, but the components in the children of this component need to be created at the beginning, which leads to unnecessary data requests and constructions for all the datatables corresponding to my menu items when the program starts ( I want to make a data request and build when the menu item is clicked).

Maybe this question is a bit too big, sorry, I will learn more and think of a way.
