### ISSUE TITLE
support null safety

### ISSUE THREAD

**Issue by alexodus** [abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard#8]
Please, support null safety. Thanks

**Comment by RounakTadvi** [comment]
Hey, you can checkout https://github.com/RounakTadvi/Flutter-Responsive-Admin-Panel-or-Dashboard 
for now also have made a PR which supports nullsafety.

**Comment by abuanwar072** [comment]
> Hey, you can checkout https://github.com/RounakTadvi/Flutter-Responsive-Admin-Panel-or-Dashboard
> for now, I also have made a PR which supports nullsafety.

merged it to the main branch
